cask_args appdir: '/Applications'
tap 'caskroom/versions'
tap 'caskroom/fonts'
tap 'argon/mas'

brew 'openssl'
brew 'readline'
brew 'coreutils'
brew 'git'
brew 'git-lfs'
brew 'bash'
brew 'bash-completion'
brew 'fasd'
brew 'fish'
brew 'curl'
brew 'wget'
brew 'httpie'
brew 'tree'
brew 'awscli'
brew 'node'
brew 'nvm'
brew 'maven'
brew 'leiningen'
brew 'heroku-toolbelt'
brew 'mas'
brew 'planck'

cask 'iterm2-beta'
cask 'sublime-text3'
cask 'font-source-code-pro'
cask 'google-chrome'
cask 'github-desktop'
cask 'slack'
cask 'gpgtools'
cask 'flux'
cask 'appcleaner'
cask 'imageoptim'
cask 'ngrok'
cask 'caffeine'
cask 'alfred'
cask 'sketch'
cask 'terraform'
cask 'packer'
cask 'java'
cask 'intellij-idea'

mas 'DaisyDisk', id: 411643860
mas 'Icon Slate', id: 439697913
mas 'Tweetbot for Twitter', id: 557168941
mas 'Xcode', id: 497799835
